### ISSUE TITLE
[Android Geofencing SDK] Expose user properties in POI object 

### ISSUE THREAD

**Issue by strider1981** [Woosmap/geofencing-core-android-sdk#19]
### What?

Expose user properties with POI object

### Why?

Reading user_properties associated with POI using the jsondata object can be difficult for clients. To simplify the process and handle it in the SDK.

### Engineering Section
1. Expose `getUserPropertyMap` method in the `POI` object which returns a Map object.

**Comment by JeanCarriere** [comment]
iOS part tested
Android part is going to be tested

**Comment by lpernelle-wgs** [comment]
Functional review ✅ 

Documentation PR: https://github.com/Woosmap/developers.woosmap.com/pull/769
